Repository multidadosti-erp/odoo, pull requests merged in 2020-02, with the labels that each got.

#49 T3997-Adaptar o Theme MUK para WEB SITE Odoo 12
  addons/website/views/website_templates.xml
Labels: Category: Frontend, Type: Improvement

#50 T3841-Traduzir o Model PORTAL Odoo 12
  addons/portal/i18n/pt_BR.po
Labels: Type: Translation

#52 T4013-Mudar Tradução do modulo 'Sale' Odoo 12
  addons/sale/i18n/pt_BR.po
  addons/sale_management/i18n/pt_BR.po
Labels: Type: Translation

#53 T4043-Acertar modulo Portal e Email de Envio do Orçamento - Odoo 12
  addons/payment/i18n/pt_BR.po
  addons/payment_transfer/i18n/pt_BR.po
  addons/portal/i18n/pt_BR.po
  addons/sale/i18n/pt.po
  addons/sale/i18n/pt_BR.po
  addons/web/i18n/pt.po
Labels: Type: Translation

#56 T4101-Remover o Modulo 'base_partner_activity_branch' e Acertar o Cadastro de Parceiros - Odoo 12
  odoo/addons/base/i18n/pt_BR.po
Labels: Type: Translation, Version: 12.0

#58 T4064-Migração runbot para 12.0
  addons/crm/tests/__init__.py
  addons/im_support/tests/__init__.py
  addons/point_of_sale/tests/__init__.py
  addons/portal/tests/__init__.py
  addons/project/tests/__init__.py
  addons/sale_management/tests/__init__.py
  addons/survey/tests/__init__.py
  addons/web/tests/__init__.py
  addons/web_editor/tests/__init__.py
  addons/website/tests/__init__.py
  odoo/addons/test_new_api/tests/__init__.py
Labels: Category: Backend, Category: Unit test, Type: Migration

#57 T4102-Adicionar Modulo para Visualização das Atividades no Calendário
  addons/mail/i18n/pt_BR.po
Labels: Type: Translation, Version: 12.0
