Repository multidadosti-erp/odoo, pull requests merged in 2020-01, with the labels that each got.

#35 T3874-Traduzir modulo BASE_IMPORT Odoo 12
  addons/base_import/i18n/pt_BR.po
Labels: Translation, Type: Migration

#36 T3882-Traduzir o Modulo "Mail" do Core - Odoo 12
  addons/mail/i18n/pt_BR.po
Labels: Translation, Type: Migration

#37 T3882-Traduzir o Modulo "Mail" do Core - Odoo 12
  addons/mail/i18n/pt_BR.po
Labels: Translation, Type: Migration

#38 T3880-Traduzir o Modulo "Sale" do Core - Odoo 12
  addons/sale/i18n/pt_BR.po
Labels: Translation, Type: Migration

#39 T3858-Traduzir o Modulo CRM do Core - Odoo 12
  addons/crm/i18n/pt_BR.po
Labels: Type: Migration

#40 T3899-Traduzir o Modulo "NOTE" do Core - Odoo 12
  addons/note/i18n/pt_BR.po
Labels: Translation, Type: Migration

#41 T3879-Traduzir o Modulo "Account" do Core - Odoo 12
  addons/account/i18n/pt_BR.po
Labels: Translation, Type: Migration

#42 T3866-Traduzir module "BASE" Odoo 12 Core
  odoo/addons/base/i18n/pt_BR.po
Labels: Translation, Type: Migration

#43 T3945-Traduzir Modulo: MAIL_BOT Odoo 12
  addons/mail_bot/i18n/pt_BR.po
Labels: Translation, Type: Migration

#45 T3958-Acerto na tradução pt_br modulo 'account' Odoo 12
  addons/account/i18n/pt_BR.po
Labels: Translation, Type: Migration

#46 T3967-Tradução de Mensagem - compor projeto
  addons/hr_timesheet/i18n/pt_BR.po
Labels: Type: Improvement, Type: Translation

#47 T3974-Acertar tradução PT_BR módulo 'inventory' do Odoo 12
  addons/stock/i18n/pt_BR.po
Labels: Type: Translation

#48 T3998-Acertar Tradução modulo 'Sale' Odoo 12
  addons/sale/i18n/pt_BR.po
Labels: Type: Migration, Type: Translation
