Repository multidadosti-erp/odoo, pull requests merged in 2021-07, with the labels that each got.

#108 T5532 - Ajustar Menu do Portal
  addons/website/models/website.py
  addons/website/tests/test_menu.py
Labels: Category: Backend, Category: Unit test, Type: Bug, Version: 12.0

#109 T5549 - Erro: Importação de Clientes, fica até dar timeout
  odoo/models.py
Labels: Priority: Highest, Type: Bug, Version: 12.0

#111 T5570 - Acertar tradução de "parceiros" para "fornecedores no cadastro de Produto na Aba Compra
  addons/product/i18n/pt_BR.po
  addons/purchase/i18n/pt_BR.po
Labels: Type: Improvement, Type: Translation, Version: 12.0

#112 T5573 - Criar opção de selecionar mais de uma variante do produto no POS da Kanxa
  addons/point_of_sale/i18n/pt_BR.po
Labels: Type: Improvement, Type: Translation, Version: 12.0

#113 T5597 - Criação de inventário não adiciona produtos sem estoque
  addons/stock/i18n/pt_BR.po
  addons/stock/views/stock_inventory_views.xml
Labels: Category: Frontend, Type: Improvement, Version: 12.0
