Repository multidadosti-erp/odoo, pull requests merged in 2021-09, with the labels that each got.

#119 T5710 - incluir valor financeiro na tela de faturas de fornecedores
  addons/account/views/account_invoice_view.xml
Labels: Category: Backend, Type: Improvement, Version: 12.0

#120 T5737 - O sistema esta sugerindo Números de Série Automaticamente
  addons/stock/i18n/pt_BR.po
Labels: Type: Translation, Version: 12.0

#125 T5773 - Adicionar o modulo MRP para uso em clientes
  addons/sale_mrp/tests/__init__.py
Labels: Type: Bug, Version: 12.0

#124 T5778 - Arrumar a tela do estoque com o padrão do sistema
  addons/stock/views/stock_location_views.xml
Labels: Category: Frontend, Type: Bug, Version: 12.0
