Repository multidadosti-erp/odoo, pull requests merged in 2021-10, with the labels that each got.

#127 T5811 - Adicionar Id do move na mensagem de erro para facilitar a Identificação
  addons/account/models/account_move.py
Labels: Category: DevOps, Type: Improvement, Version: 12.0

#129 T5836 - Adicionar nas Configurações dos Campos da Tree o Nome para não misturar com outras visões
  odoo/addons/base/rng/tree_view.rng
Labels: Type: Improvement, Version: 12.0

#132 T5850 - O sistema esta filtrando de forma errada os clientes no POS
  addons/point_of_sale/models/res_partner.py
  addons/point_of_sale/static/src/js/models.js
Labels: Category: Backend, Priority: Highest, Type: Bug, Version: 12.0
