Repository multidadosti-erp/odoo, pull requests merged in 2022-04, with the labels that each got.

#159 T6239 - Reorganização de impressão
  addons/mail/models/mail_template.py
Labels: Category: Backend, Type: Improvement, Version: 12.0

#160 T6242 - Ajustar Tela de Compras
  addons/purchase/views/purchase_views.xml
Labels: Category: Backend, Type: Improvement, Version: 12.0

#161 T6218 - Acesso por equipe em projetos
  addons/project/i18n/pt_BR.po
Labels: Type: Bug, Version: 12.0

#162 T6324 - Erro: Plano de Contas com mais de uma Empresa
  odoo/fields.py
  odoo/models.py
Labels: Priority: Highest, Type: Improvement, Version: 12.0
