Repository multidadosti-erp/odoo, pull requests merged in 2022-08, with the labels that each got.

#171 T6597 - Alterar origem dos valores de TIPO DE TITULO e OPERAÇÃO FINANCEIRA do POS
  addons/point_of_sale/i18n/pt_BR.po
Labels: Type: Translation, Version: 12.0

#172 T6584 - Sugestão/Criação Nº Série
  addons/web/static/src/js/fields/relational_fields.js
Labels: Category: Frontend, Type: Improvement, Version: 12.0

#170 T6540 - Exclui cadastro de campanhas
  addons/utm/models/utm.py
  addons/utm/security/ir.model.access.csv
Labels: Type: Improvement, Version: 12.0

#173 T6582 - Equipe de atividades
  addons/crm/models/crm_lead.py
Labels: Type: Bug, Version: 12.0
