Repository multidadosti-erp/odoo, pull requests merged in 2022-09, with the labels that each got.

#174 T6671 - Criação de Novos Tipos de Parceiros
  odoo/models.py
Labels: Type: New feature, Version: 12.0

#175 T6686 - Erro no Core do Odoo por não tratar lot por empresa
  addons/stock/models/stock_production_lot.py
Labels: Version: 12.0

#178 T6623 - Criação de Modelo de Etiqueta de Separação de Itens
  addons/delivery/views/delivery_view.xml
  addons/stock/views/stock_quant_views.xml
Labels: Category: Frontend, Type: Improvement, Version: 12.0
