Repository multidadosti-erp/odoo, pull requests merged in 2022-07, with the labels that each got.

#166 T6514 - Menu sobrepondo informações
  addons/web/static/src/js/views/form/form_renderer.js
Labels: Category: Frontend, Type: Bug, Version: 12.0

#167 T6553 - Verificação do erro ao tentar cancelar pedido de venda
  addons/sale_stock/models/sale_order.py
Labels: Priority: Highest, Type: Bug, Version: 12.0

#165 T6458 - Adicionar aos Contratos de Serviço: Eventos de Horas e Despesas
  addons/hr_expense/views/hr_expense_views.xml
Labels: Category: Frontend, Type: Improvement, Version: 12.0
