Repository multidadosti-erp/odoo, pull requests merged in 2023-09, with the labels that each got.

#228 T7795 - Duplicação de itens
  addons/stock/models/stock_picking.py
  addons/stock/views/stock_picking_views.xml
Labels: Category: Backend, Category: Frontend, Priority: High, Type: Bug, Version: 12.0

#229 T7802 - Ajustes nas Mudanças do Multiphono
  addons/web/static/src/js/views/kanban/kanban_column.js
  addons/web/static/src/js/views/kanban/kanban_renderer.js
  addons/web/static/src/js/views/kanban/kanban_view.js
Labels: Category: Frontend, Type: Improvement, Version: 12.0

#232 T7582 - Entrada/validação NF 62553
  addons/account/models/account_invoice.py
Labels: Type: Bug, Version: 12.0

#234 T7844 - Liberar a Alteração do Diário na Invoice de Compras
  addons/account/views/account_invoice_view.xml
Labels: Category: Frontend, Type: Improvement, Version: 12.0

#235 T7842 - Ajustes no Widget Thread após a separação de mensagens e logs
  addons/mail/static/src/js/models/threads/thread.js
Labels: Category: Frontend, Priority: Highest, Type: Improvement, Version: 12.0
