Repository multidadosti-erp/odoo, pull requests merged in 2023-07, with the labels that each got.

#216 T7467 - Lançar Despesas no Conta Corrente do Funcionário
  addons/sale_expense/tests/__init__.py
Labels: Category: Backend, Category: Unit test, Type: Bug, Version: 12.0

#217 T7589 - Erro "Valor total e parcelas divergentes" ao confirmar faturas importadas via XML
  addons/account/models/account_payment.py
Labels: Category: Backend, Priority: Highest, Type: Bug

#218 T7574 - Erro no campo Diferença dos Diarios Financeiros
  addons/account/i18n/account.pot
  addons/account/i18n/pt_BR.po
  addons/account/models/account_journal_dashboard.py
  addons/account/models/reconciliation_widget.py
  addons/account/views/account_journal_dashboard_view.xml
Labels: Category: Frontend, Status: Impediment, Type: Translation, Version: 12.0

#219 T7647 - Alterações Solicitadas pelo Cliente
  addons/account/i18n/pt_BR.po
  addons/account/views/account_payment_view.xml
Labels: Type: Improvement, Version: 12.0
