Repository multidadosti-erp/odoo, pull requests merged in 2023-08, with the labels that each got.

#220 T7663 - Relatório Itens de Estoque na empresa Osasco
  addons/stock/views/stock_quant_views.xml
Labels: Category: Frontend, Type: Bug, Version: 12.0

#221 T7716 - Odoo está apagando stock_quant dos lot zerados, causando problemas nos relatórios
  addons/stock/models/stock_quant.py
Labels: Priority: High, Version: 12.0

#222 T7697 - Relatório de Inventário - Add coluna código do item
  addons/stock/views/stock_quant_views.xml
Labels: Category: Frontend, Version: 12.0

#224 T7769 - O sistema altera o valor unitario do item apos recarregar a Posição Fiscal
  addons/account/models/account_invoice.py
Labels: Category: Backend, Priority: Highest, Type: Bug

#223 T7759 - Saldo do Estoque Atual
  addons/stock/i18n/pt_BR.po
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/views/stock_quant_views.xml
Labels: Category: Frontend, Type: Translation, Version: 12.0

#225 T7728 - Melhorias Gestão Tickets
  odoo/addons/base/views/res_partner_views.xml
Labels: Category: Backend, Version: 12.0

#226 T7681 - Criar novo Kanban para visualizar melhor as Atividades
  addons/web/static/src/js/views/kanban/kanban_record.js
Labels: Category: Frontend, Priority: High, Type: Improvement, Version: 12.0
