Repository multidadosti-erp/odoo, pull requests merged in 2023-04, with the labels that each got.

#205 T7173 - E-mail de convite de reunião enviado em Ingles
  addons/calendar/data/mail_data.xml
  addons/calendar/i18n/calendar.pot
  addons/calendar/i18n/pt_BR.po
Labels: Type: Bug, Type: Translation

#207 T7198 - Ajustar visibilidade do usuario admin
  addons/sale/tests/test_sale_order.py
Labels: Priority: Highest, Type: Improvement

#208 T7215 - Erro de estoque no Cancelamento de Separação
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
Labels: Priority: Highest, Type: Bug, Version: 12.0

#209 T7235 - Adiciona Botão para Identificar duplicações nas Oportunidades
  addons/crm/views/crm_lead_views.xml
Labels: Type: New feature, Version: 12.0
