Repository multidadosti-erp/odoo, pull requests merged in 2024-08, with the labels that each got.

#283 T8581 - Criar a Opção de Descontar Título Manualmente
  addons/account/data/account_data.xml
  addons/account/models/account_payment.py
Labels: Category: Backend, Type: New feature

#285 T8581 - Criar a Opção de Descontar Título Manualmente
  addons/account/data/account_data.xml
  addons/account/models/account_payment.py
Labels: Type: Improvement

#287 T8636 - Gerar Contratos de Serviço de Eventos Fixos e Recorrentes com valores líquidos para o Fluxo de Caixa
  addons/account/models/account_invoice.py
Labels: Type: Improvement, Version: 12.0

#288 T8643 - Adicionar no Kanban de Projetos Tarefas e Agendas em Aberto
  addons/project/views/project_views.xml
Labels: Category: Frontend, Version: 12.0

#289 T8653 - Erro de Duplicidade de Produtos na Separação de Estoque
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_picking.py
Labels: Priority: Highest, Type: Bug, Version: 12.0

#292 T8669 - Sistema está enviado e-mail de alerta mesmo com a opção desmarcada
  addons/calendar/models/calendar.py
Labels: Category: Backend, Type: Bug
