Repository multidadosti-erp/odoo, pull requests merged in 2024-04, with the labels that each got.

#263 T8330 - Usabilidade melhoria ticket TI-09712 - Solicitação de compra empresa do grupo
  addons/purchase/views/purchase_views.xml
Labels: Category: Frontend, Type: Improvement

#264 T8353 - Adicionar Agendas aos Itens do Pedido do Tipo PROJETO CONTRATO DE ALOCAÇÃO
  addons/account/models/account_invoice.py
Labels: Type: Improvement, Version: 12.0

#266 T8377 - Erro ao Importar Clientes
  odoo/addons/base/models/res_partner.py
Labels: Priority: Highest, Type: Bug, Version: 12.0
