Repository multidadosti-erp/odoo, pull requests merged in 2024-05, with the labels that each got.

#268 T8337 - Discussão TI-09944 - Edição N/S (Criação de Numero Lote/Numero de Serie)
  addons/stock/models/stock_production_lot.py
Labels: Category: Backend, Category: Frontend, Version: 12.0

#270 T8371 - Sistema está permitindo dar a entrada do mesmo numero de série em locais diferentes ao mesmo tempo
  addons/stock/models/stock_quant.py
Labels: Type: Improvement, Version: 12.0

#272 T8412 - Adicionar no Contrato de Serviço a Moeda para Faturamento
  addons/account/models/account_invoice.py
  addons/account/models/account_move.py
  addons/account/views/account_view.xml
Labels: Type: Improvement, Version: 12.0

#273 T8410 - Integrar novo sistema de cadastro de certificados na consulta do SEFAZ
  odoo/tools/config.py
Labels: Category: Backend, Type: Improvement
