Repository multidadosti-erp/odoo, pull requests merged in 2024-03, with the labels that each got.

#257 T8295 - Adicionar na Agenda o Status: RESERVADA
  addons/calendar/i18n/pt_BR.po
  addons/calendar/models/calendar.py
Labels: Category: Frontend, Type: Improvement, Version: 12.0

#258 T8297 - Adicionar funcionalidade de Criar Campos dinâmicos no BR_BASE
  addons/web/static/src/js/views/form/form_controller.js
Labels: Type: Improvement, Version: 12.0

#259 T8294 - OutLook não adiciona automaticamente a Agenda
  addons/calendar/models/calendar.py
Labels: Category: Backend, Priority: Highest, Type: Bug

#260 T8302 - Ajustes na integração da Lawps (Despesas)
  addons/hr_expense/i18n/pt_BR.po
Labels: Type: Translation, Version: 12.0
