Repository multidadosti-erp/odoo, pull requests merged in 2024-10, with the labels that each got.

#299 T8673 - Criar Visão da Dash para Contratos
  addons/project/views/project_views.xml
Labels: Category: Frontend, Type: Improvement, Version: 12.0

#301 T8778 - Ajustes na Nova Tela de Dash de Eventos do Contrato
  addons/mail/models/mail_thread.py
Labels: Category: Backend, Priority: High, Type: Bug, Type: Translation, Version: 12.0

#300 T8755 - Contratos nao estão atualizando/gerando os evento automaticamente - valores sem atualização automática
  addons/web/static/src/js/chrome/abstract_web_client.js
  odoo/models.py
Labels: Category: Frontend, Type: Bug, Version: 12.0

#303 T8799 - Sistema esta Deixando Inativar Estoques com Saldo dos Produtos
  addons/stock/i18n/pt_BR.po
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_location.py
Labels: Type: Improvement, Type: Translation, Version: 12.0

#304 T8746 - Tradução de Email com Instruções de Login no Portal de Tickets.
  addons/auth_signup/data/auth_signup_data.xml
  addons/auth_signup/i18n/auth_signup.pot
  addons/auth_signup/i18n/pt_BR.po
Labels: Category: Frontend, Type: Translation, Version: 12.0

#306 T8827 - Ajustes Contrato Tipo Hora
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/models/res_lang.py
Labels: Category: Backend, Priority: High, Type: Bug, Type: Translation, Version: 12.0
