Repository multidadosti-erp/odoo, pull requests merged in 2025-06, with the labels that each got.

#356 T9255 - Erro no POS: Ao gerar Invoice do POS esta pegando empresa Errada nos Itens
  addons/point_of_sale/models/pos_order.py
Labels: Priority: Highest, Type: Bug, Version: 12.0

#355 T9211 - Ajusta a Cor dos Itens Separados no Stock Picking
  addons/web/static/lib/bootstrap/scss/_variables.scss
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web/static/src/scss/form_view.scss
Labels: Category: Frontend, Priority: High, Type: Improvement, Version: 12.0

#360 T9085 - Alterações/Correções Portal
  addons/account/views/account_portal_templates.xml
Labels: Category: Frontend, Type: Improvement, Version: 12.0
