Repository multidadosti-erp/odoo, pull requests merged in 2025-04, with the labels that each got.

#335 T9124 - Imposto duplicado ao Editar fatura vinda de Contrato
  addons/account/models/account.py
  addons/account/models/account_invoice.py
Labels: Priority: Highest, Type: Bug, Version: 12.0

#336 T8967 - o sistema não pode permitir alterações de itens da fatura quando a separação já estiver sido validada.
  addons/web/static/src/js/fields/relational_fields.js
Labels: Category: Frontend, Priority: High, Type: Bug, Version: 12.0

#338 T9110 - Título Descontado ao ser estornado não volta para o Status Título Descontado
  addons/account/models/account_payment.py
Labels: Type: Improvement, Version: 12.0

#340 T9167 - Corrigir aliquota dos impostos ICMS, PIS e Cofins em faturas do POS
  addons/point_of_sale/views/pos_order_view.xml
Labels: Category: Frontend, Type: Improvement
