Repository multidadosti-erp/odoo, pull requests merged in 2025-02, with the labels that each got.

#323 T8957 - Data errada de aviso de Atividade
  addons/mail/models/mail_activity.py
Labels: Category: Backend, Type: Bug, Version: 12.0

#324 T9005 - Remover campo "Não associe a um cliente", ao realizar a conversão de prospecto para oportunidade.
  addons/crm/wizard/crm_partner_binding.py
Labels: Category: Frontend

#325 T8990 - Ao Criar uma Folga, espelhar no Calendário
  addons/web/static/lib/fullcalendar/js/fullcalendar.js
Labels: Category: Frontend, Type: Improvement, Version: 12.0
