Repository multidadosti-erp/odoo, pull requests merged in 2025-08, with the labels that each got.

#370 T9382 - Erro JavaScript
  addons/web_tour/static/src/js/tip.js
Labels: Category: Frontend, Type: Bug, Version: 12.0

#372 T9356 - Ao faturar eventos de contrato o sistema está atribuindo o usuário como seguindo e disparando e-mails
  addons/mail/models/mail_thread.py
Labels: Category: Backend, Type: Bug, Version: 12.0

#377 T9185 - Alteração Tela de Inclusão de Horas (Planilha de Horas)
  addons/hr_timesheet/views/hr_timesheet_views.xml
Labels: Category: Frontend, Type: Improvement

#376 T9412 - Erro ao Criar Consulta - Evoluir Validação
  addons/website/models/website.py
  odoo/api.py
  odoo/http.py
  odoo/tools/cache.py
Labels: Type: New feature, Version: 12.0
