Repository multidadosti-erp/odoo, pull requests merged in 2025-05, with the labels that each got.

#342 T9177 - Ao Aprovar uma Oportunidade o Valor esta sendo Zerado
  addons/sale_crm/i18n/pt_BR.po
  addons/sale_crm/i18n/sale_crm.pot
  addons/sale_crm/models/crm_lead.py
Labels: Type: Improvement, Type: Translation, Version: 12.0

#346 T9139 - Criar Tabela de Preço por Item relacionado ao Cliente
  addons/product/i18n/product.pot
Labels: Type: Bug, Type: Translation, Version: 12.0

#347 T9192 - Adicionar opção Condição de Pagamento para Tratar Data do Faturamento do Contrato
  addons/account/models/account_invoice.py
Labels: Type: Improvement, Version: 12.0

#348 T9013 - Conversão de unidades de compra por fatura e importação de xml
  addons/account/models/account_invoice.py
Labels: Category: Backend, Type: Bug

#349 T9206 - Ajustes nas Condições de Pagamento
  addons/account/i18n/account.pot
  addons/account/i18n/ar.po
  addons/account/i18n/az.po
  addons/account/i18n/bg.po
  addons/account/i18n/bn.po
  addons/account/i18n/bs.po
  addons/account/i18n/ca.po
  addons/account/i18n/cs.po
  addons/account/i18n/da.po
  addons/account/i18n/de.po
  addons/account/i18n/el.po
  addons/account/i18n/es.po
  addons/account/i18n/et.po
  addons/account/i18n/eu.po
  addons/account/i18n/fa.po
  addons/account/i18n/fi.po
  addons/account/i18n/fil.po
  addons/account/i18n/fr.po
  addons/account/i18n/gu.po
  addons/account/i18n/he.po
  addons/account/i18n/hr.po
  addons/account/i18n/hu.po
  addons/account/i18n/id.po
  addons/account/i18n/is.po
  addons/account/i18n/it.po
  addons/account/i18n/ja.po
  addons/account/i18n/ka.po
  addons/account/i18n/kab.po
  addons/account/i18n/km.po
  addons/account/i18n/ko.po
  addons/account/i18n/lt.po
  addons/account/i18n/lv.po
  addons/account/i18n/mn.po
  addons/account/i18n/nb.po
  addons/account/i18n/nl.po
  addons/account/i18n/pl.po
  addons/account/i18n/pt.po
  addons/account/i18n/pt_BR.po
  addons/account/i18n/ro.po
  addons/account/i18n/ru.po
  addons/account/i18n/sk.po
  addons/account/i18n/sl.po
  addons/account/i18n/so.po
  addons/account/i18n/sr.po
  addons/account/i18n/sv.po
  addons/account/i18n/ta.po
  addons/account/i18n/th.po
  addons/account/i18n/tr.po
  addons/account/i18n/uk.po
  addons/account/i18n/vi.po
  addons/account/i18n/zh_CN.po
  addons/account/i18n/zh_TW.po
  addons/account/views/account_view.xml
Labels: Category: Frontend, Type: Translation, Version: 12.0

#350 T9231 - Adicionar aos Menus e SubMenus do Sistema opção de web_icon
  addons/web/static/src/xml/menu.xml
  odoo/tools/convert.py
Labels: Category: Frontend, Version: 12.0
