Repository multidadosti-erp/odoo, pull requests merged in 2025-03, with the labels that each got.

#326 T9068 - Adicionar as Anotações Internas dos Produtos nos Itens do Orçamento
  addons/product/views/product_views.xml
Labels: Category: Frontend, Version: 12.0

#329 T9002 - Permitir cancelar separação de orçamento de locação sem contrato vinculado
  addons/account/models/chart_template.py
Labels: Category: Backend, Stage: Testing

#327 T9067 - Incluir somatória para a coluna " Taxas Excluídas"
  odoo/models.py
Labels: Category: Frontend, Type: Improvement, Version: 12.0

#330 T9080 - Melhorar a Performance da Fatura
  addons/account/models/account_invoice.py
Labels: Type: Improvement, Version: 12.0

#333 T9109 - Erro ao acessar faturas pelo parceiro
  addons/account/models/account_invoice.py
Labels: Priority: Highest, Type: Bug, Version: 12.0

#332 T9074 - Ajuste Filtro (Oportunidades) e Add Filtro (Atividades)
  addons/web/static/src/js/core/domain.js
Labels: Category: Frontend, Type: Bug, Version: 12.0
