Repository multidadosti-erp/odoo, pull requests merged in 2025-01, with the labels that each got.

#315 T8911 - Erros de tradução
  addons/crm/i18n/pt_BR.po
  addons/link_tracker/i18n/pt_BR.po
  addons/utm/i18n/pt_BR.po
  addons/website_sale_link_tracker/i18n/pt_BR.po
Labels: Type: Translation

#316 T8839 - Corrigir Visão do Calendario com base na permissão do usuario
  addons/web/static/src/js/views/calendar/calendar_model.js
Labels: Category: Frontend, Type: Improvement

#317 T8937 - Criar Verificação de Acesso da Atividade ao MODEL que esta vinculada
  odoo/models.py
Labels: Type: Improvement, Version: 12.0

#319 T8936 - Criar Regra de Acesso ao Calendário
  addons/calendar/__manifest__.py
  addons/calendar/i18n/pt_BR.po
  addons/calendar/security/calendar_security.xml
  addons/calendar/security/ir.model.access.csv
  addons/calendar/tests/test_calendar.py
  addons/calendar/views/calendar_views.xml
  addons/hr_holidays/tests/common.py
  addons/web/static/src/js/views/calendar/calendar_model.js
  odoo/addons/base/data/ir_module_category_data.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/i18n/pt_BR.po
Labels: Category: Backend, Type: Improvement

#320 T8941 - Títulos Cancelados - Está permitindo Alterar Data e Valor
  addons/account/i18n/account.pot
  addons/account/i18n/pt_BR.po
  addons/account/views/account_journal_dashboard_view.xml
  addons/account/views/account_payment_view.xml
Labels: Category: Frontend, Type: Translation, Version: 12.0
