Repository multidadosti-erp/odoo, pull requests merged in 2025-07, with the labels that each got.

#362 T9082 - Multi Idioma aviso Invoice Português @
  addons/account/i18n/pt.po
  addons/account/i18n/pt_BR.po
  addons/auth_signup/i18n/pt.po
  addons/event/i18n/pt.po
  addons/portal/i18n/pt.po
  addons/purchase/i18n/pt.po
  addons/purchase/i18n/pt_BR.po
Labels: Type: Translation, Version: 12.0

#361 T9286 - Erro de Arredondamento do IR em NFs de Serviço
  addons/account/models/account_invoice.py
Labels: Category: Backend, Type: Bug

#365 T9306 - Relatório de estoque atual não ordena por nro de série
  addons/stock/models/stock_production_lot.py
Labels: Category: Backend, Type: Bug

#366 T9322 - Corrigir mensagem ao cancelar fatura com titulo cancelado
  addons/account/models/account_invoice.py
Labels: Priority: Highest, Type: Bug, Version: 12.0
